VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "ClsName"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
'Start here
Function AWX(MyNum As Single) As String
    '*/*/*/* PLEASE RATE */*/*/*'
    '*/*/*/* PLEASE RATE */*/*/*'
    '*/*/*/* PLEASE RATE */*/*/*'
    
    'A function called AWX was created
    'And a simple line of code:
    AWX = CSng(MyNum * 5) & vbCrLf & "Any Text"
End Function
